name: Build

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Examine suspicious constructs
        run: |
          go vet ./...
      
      - name: Look for vulnerabilities
        run: |
          govulncheck ./...

    